### ISSUE TITLE
Eshint on Windows

### ISSUE THREAD

**Issue by simlu** [FGRibreau/check-build#72]
Getting weird errors when trying to use eslint on windows. Any idea?

```
[eslint]
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at Object.exec (...\node_modules\check-build\src\interface\_utils.js:108:5)
    at ...\node_modules\check-build\src\interface\eslint.js:23:11
    at checkModuleInterface (...\node_modules\check-build\src\checkBuild.js:44:20)
    at ...\node_modules\check-build\src\checkBuild.js:26:9
    at ...\node_modules\async\lib\async.js:375:13
    at Immediate.iterate (...\node_modules\async\lib\async.js:262:13)
    at runCallback (timers.js:672:20)
npm ERR! Test failed.  See above for more details.
```

**Comment by FGRibreau** [comment]
Check-build was not tested on windows only on mac & linux so this might be related, don't hesitate to send a PR that fix this :)
