### ISSUE TITLE
.istanbul.yml with default-excludes: false

### ISSUE THREAD

**Issue by simlu** [FGRibreau/check-build#73]
When changing `default-excludes` to false the coverage report starts failing with the following error message:

```
Failed to parse file: ...\node_modules\acorn-jsx\node_modules\acorn\dist\acorn_loose.es.js

...\node_modules\istanbul\lib\instrumenter.js:468
                throw e;
                ^
Error: Line 1: Unexpected token
    at constructError (...\node_modules\istanbul\node_modules\esprima\esprima.js:2407:21)
    at createError (...\node_modules\istanbul\node_modules\esprima\esprima.js:2426:17)
    at unexpectedTokenError (...\node_modules\istanbul\node_modules\esprima\esprima.js:2500:13)
    at tolerateUnexpectedToken (...\node_modules\istanbul\node_modules\esprima\esprima.js:2509:21)
    at parseStatementListItem (...\node_modules\istanbul\node_modules\esprima\esprima.js:3973:21)
    at parseFunctionSourceElements (...\node_modules\istanbul\node_modules\esprima\esprima.js:4869:23)
    at parseFunctionExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:5074:16)
    at parsePrimaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3273:24)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (...\node_modules\istanbul\node_modules\esprima\esprima.js:3414:20)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parsePostfixExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3490:16)
    at parseUnaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3550:20)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseBinaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3639:16)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseConditionalExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3696:16)
    at parseAssignmentExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3893:16)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseGroupExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3162:16)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parsePrimaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3239:20)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (...\node_modules\istanbul\node_modules\esprima\esprima.js:3414:20)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parsePostfixExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3490:16)
    at parseUnaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3550:20)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseBinaryExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3639:16)
    at inheritCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2681:18)
    at parseConditionalExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3696:16)
    at parseAssignmentExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3893:16)
    at isolateCoverGrammar (...\node_modules\istanbul\node_modules\esprima\esprima.js:2663:18)
    at parseExpression (...\node_modules\istanbul\node_modules\esprima\esprima.js:3942:16)
    at parseExpressionStatement (...\node_modules\istanbul\node_modules\esprima\esprima.js:4222:20)
    at parseStatement (...\node_modules\istanbul\node_modules\esprima\esprima.js:4760:24)
    at parseStatementListItem (...\node_modules\istanbul\node_modules\esprima\esprima.js:3989:16)
    at parseScriptBody (...\node_modules\istanbul\node_modules\esprima\esprima.js:5490:25)
    at parseProgram (...\node_modules\istanbul\node_modules\esprima\esprima.js:5506:16)
    at Object.parse (...\node_modules\istanbul\node_modules\esprima\esprima.js:5690:23)
    at Object.instrumentSync (...\node_modules\istanbul\lib\instrumenter.js:459:31)
    at ...\node_modules\istanbul\lib\command\common\run-with-cover.js:224:33
    at Array.forEach (native)
    at process.<anonymous> (...\node_modules\istanbul\lib\command\common\run-with-cover.js:222:39)
    at process.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:164:15)
    at done (...\node_modules\mocha\bin\_mocha:490:15)
    at afterWrite (_stream_writable.js:385:3)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! Test failed.  See above for more details.

```

**Comment by FGRibreau** [comment]
Hello :)

It related with istanbul not check-build you might want to submit your issue there :)

**Comment by simlu** [comment]
Kk, thanks!
